Implement QueryHelper
hoverla-bobocode/Bibernate pull request #5
Opened 2022-09-04 16:40 UTC by yakovenkoua

2022-09-04 21:52 UTC, StanislavZabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +public class QueryHelper {
Could you also add a method to persist data?

2022-09-04 21:52 UTC, StanislavZabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +            throw new QueryHelperException("Transaction is rolled back", e);
In my opinion, we don't need a new custom exception for this class, we can just reuse the generic BibernateException here. What do you think?

2022-09-04 21:52 UTC, StanislavZabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +    public <T> T readWithinTx(Function<Session, T> entityManagerConsumer) {
Please add unit tests.

2022-09-05 07:01 UTC, DanielChanger requested changes

2022-09-05 07:01 UTC, DanielChanger commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +    public <T> T readWithinTx(Function<Session, T> entityManagerConsumer) {
it's not only for read. Please rename this method to runWithinTxReturning, and create another one runWithinTx that returns void

2022-09-05 07:01 UTC, DanielChanger commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +    public <T> T readWithinTx(Function<Session, T> entityManagerConsumer) {
please make these methods static and QueryHelper constructor private

2022-09-05 07:02 UTC, DanielChanger commented
Write Unit Tests

2022-09-06 17:50 UTC, StanislavZabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +            return null;
Just a tip: It doesn't look very good from a reading perspective.As for me, I would rather duplicate the try catch block here.

2022-09-06 17:52 UTC, StanislavZabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +    public static <T> T runWithinTxReturning(SessionFactory sessionFactory, Function<Session, T> sessionConsumer) {
Actually we can`t call the second parameter with suffix "consumer" as it is Function, not a consumer

2022-09-15 06:45 UTC, StanislavZabramnyi approved these changes, later dismissed
👍😉✌️😎

2022-09-15 06:51 UTC, DanielChanger requested changes
Add docs plz

2022-09-15 06:51 UTC, DanielChanger commented on src/test/java/com/bobocode/bibernate/integration/QueryHelperIntegrationTest.java
> +                (session_) -> session_.find(Product.class, 1L));
(nit) _ is typo

2022-09-15 06:51 UTC, DanielChanger commented on src/test/resources/persistence.yml
> +logLevel: TRACE
remove plz

2022-09-15 09:37 UTC, szabramnyi submitted a review, later dismissed
👍😉

2022-09-15 09:37 UTC, szabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +     * Creates a new session using the provided session factory and performs the passed action within the session scope.
(nit) would be good to add link to the SessionFactory using {@link SessionFactory}

2022-09-15 09:37 UTC, szabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +     * Creates a new session using the provided session factory and performs the passed action within the session scope.
the same for Session

2022-09-15 09:37 UTC, szabramnyi commented on src/main/java/com/bobocode/bibernate/QueryHelper.java
> +     * Provided logic is run within transaction scope, which will be either committed or rollback (in case exception happens).
the same for Transaction

2022-09-15 09:39 UTC, DanielChanger submitted a review, later dismissed

2022-09-15 09:57 UTC, StanislavZabramnyi submitted a review, later dismissed
🤗

2022-09-15 10:16 UTC, DanielChanger approved these changes
LGTM, well done

2022-09-15 11:22 UTC, merged